# Generated by Django 5.1.1 on 2024-10-12 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
            preserve_default=False,
        ),
    ]
